"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cnpjPatternArrayOne = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];
exports.cnpjPatternArrayTwo = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];
exports.cpfPatternArrayOne = [10, 9, 8, 7, 6, 5, 4, 3, 2];
exports.cpfPatternArrayTwo = [11, 10, 9, 8, 7, 6, 5, 4, 3, 2];
exports.alphabet = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
];
//# sourceMappingURL=index.js.map